### PR TITLE
requested update by Kiuwan

### PR DESCRIPTION
**Pull request by hblankenship**

### CODE REVIEW

**Comment by davewichers** [comment]
I prefer the current language.

**Comment by hblankenship** [comment]
It's your call; it was a request from Kiuwan to Kelly that the language changes.  If they have any questions, you are okay with having them contact you?

**Comment by davewichers** [comment]
Of course. I would prefer they contact me directly anyway.

**Comment by davewichers** [comment]
I haven't heard anything back from Kiuwan about this so closing this request.

**Pull request closed without merging**
